const storageKey='orvia-workspace-v1',welcomeKey='orvia-welcome-v1';
const stages=['Novo','Contato','Qualificado','Proposta','Negociação','Ganho','Perdido'];
const sellers=['Júlia','Camila','Rafael'];
const definitions={Novo:'Lead cadastrado, ainda sem contato realizado.',Contato:'Primeiro contato já realizado com o lead.',Qualificado:'Necessidade identificada, aderência ao produto ou serviço confirmada e interesse real em avançar.',Proposta:'Proposta comercial apresentada ou enviada.',Negociação:'Preço, prazo, escopo ou condições comerciais estão sendo discutidos.',Ganho:'Venda confirmada.',Perdido:'Oportunidade encerrada sem conversão.'};
const rawSeed=[['Mariana Costa','Aurora Arquitetura','Júlia','Sistema de Gestão','Indicação','Negociação',4500,'2026-09-18',''],['Gustavo Lima','Norte Solar','Camila','CRM Comercial','Google','Proposta',6800,'2026-09-15',''],['Renata Alves','Ateliê Nuvem','Júlia','Portal do Cliente','Instagram','Contato',3200,'2026-09-14',''],['Caio Mendes','Métrica Contábil','Rafael','Automação Financeira','Prospecção','Qualificado',5400,'2026-09-12',''],['Patrícia Rocha','Casa Aroeira','Camila','Sistema de Gestão','WhatsApp','Novo',2400,'2026-09-11',''],['Diego Santos','Elo Transportes','Rafael','Sistema de Gestão','Evento','Ganho',8900,'2026-09-09','2026-09-09'],['Carla Freitas','Viva Odonto','Júlia','CRM Comercial','Site','Ganho',4200,'2026-09-08','2026-09-08'],['Felipe Nunes','Brisa Foods','Camila','Automação Financeira','Google','Negociação',7200,'2026-09-06',''],['Lívia Amaral','Estúdio Círculo','Júlia','Portal do Cliente','Instagram','Proposta',3900,'2026-09-04',''],['Bruno Reis','Ação Log','Rafael','Sistema de Gestão','Indicação','Contato',6100,'2026-08-28',''],['Ana Beatriz','Nexo Escola','Camila','CRM Comercial','WhatsApp','Qualificado',2800,'2026-08-25',''],['Rafael Duarte','Plano Verde','Rafael','Automação Financeira','Prospecção','Perdido',5000,'2026-08-23',''],['Juliana Melo','Café Duna','Júlia','CRM Comercial','Evento','Ganho',3600,'2026-08-19','2026-08-19'],['Henrique Vilela','Axis Engenharia','Camila','Sistema de Gestão','Google','Novo',7900,'2026-08-17',''],['Tainá Luz','Lumi Casa','Júlia','Portal do Cliente','Instagram','Contato',3300,'2026-08-14',''],['Marcelo Vieira','Ponto Farma','Rafael','CRM Comercial','Indicação','Proposta',5800,'2026-08-10',''],['Sofia Marques','Arco Legal','Camila','Sistema de Gestão','Site','Negociação',4400,'2026-08-08',''],['Eduardo Silva','Terra Alta','Rafael','Automação Financeira','Google','Ganho',9700,'2026-08-04','2026-08-04'],['Camila Azevedo','Nina Decor','Júlia','Sistema de Gestão','WhatsApp','Novo',3100,'2026-07-29',''],['João Pedro','Giro Eventos','Camila','CRM Comercial','Evento','Perdido',4000,'2026-07-23',''],['Natália Prado','Ciclo Tech','Rafael','Portal do Cliente','Prospecção','Qualificado',6500,'2026-07-18',''],['Vitor Ramos','Ativa Saúde','Júlia','Automação Financeira','Indicação','Ganho',5600,'2026-07-11','2026-07-11']];
const seed=rawSeed.map((x,i)=>({id:'seed-'+i,name:x[0],company:x[1],seller:x[2],product:x[3],origin:x[4],stage:x[5],value:x[6],date:x[7],closedDate:x[8],note:'',lossReason:''}));
const $=s=>document.querySelector(s);
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const same=(date,period)=>!!date&&date.slice(0,7)===period;
const isOpen=lead=>!['Ganho','Perdido'].includes(lead.stage);
const dateText=date=>date?new Date(date+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const key=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function normal(lead){const item={...lead,value:Number(lead.value||0),note:lead.note||'',lossReason:lead.lossReason||''};if(item.stage==='Ganho'&&!item.closedDate)item.closedDate=item.date;if(item.stage!=='Ganho')item.closedDate='';return item}
function load(){try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');return Array.isArray(saved)?saved.map(normal):seed.map(normal)}catch{return seed.map(normal)}}
let leads=load();
const state={period:'2026-09',dashboardSeller:'',profileSeller:''};
const icon={dashboard:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>',users:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',workflow:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><path d="M9 6h6M18 9v6M6 9v9c0 2 2 3 4 3h5"/></svg>',badge:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="9" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2M8 3h8l1 3H7l1-3Z"/></svg>',book:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg>',arrowLeft:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6M9 12h11"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',info:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg>'};
function icons(scope=document){scope.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon[n.dataset.icon==='arrow-left'?'arrowLeft':n.dataset.icon]||'')}
function all(seller=''){return seller?leads.filter(l=>l.seller===seller):leads}
function entered(seller=''){return all(seller).filter(l=>same(l.date,state.period))}
function won(seller=''){return all(seller).filter(l=>l.stage==='Ganho'&&same(l.closedDate,state.period))}
function opened(seller=''){return entered(seller).filter(isOpen)}
function metric(seller=''){const input=entered(seller),wins=won(seller),open=opened(seller),revenue=wins.reduce((a,l)=>a+l.value,0),pipeline=open.reduce((a,l)=>a+l.value,0);return{input,wins,open,revenue,pipeline,ticket:wins.length?revenue/wins.length:0,conversion:input.length?wins.length/input.length*100:0}}
function periodLabel(){return months[Number(state.period.slice(5))-1]+' de '+state.period.slice(0,4)}
function tip(label,text){return '<button type="button" class="info-button tooltip-trigger" aria-label="'+esc(label)+'" aria-expanded="false" data-tooltip="'+esc(text)+'" data-icon="info"></button>'}
function kpis(data,profile=false){const list=profile?[['Leads ativos',data.open.length,'em acompanhamento','Quantidade de oportunidades comerciais que continuam em andamento.\nCálculo: leads que não estão marcados como Ganho ou Perdido.'],['Vendas ganhas',data.wins.length,'fechadas no período','Quantidade de oportunidades convertidas em venda.\nCálculo: leads em Ganho pela data de fechamento.'],['Conversão',data.conversion.toFixed(1)+'%','vendas ganhas ÷ entradas','Percentual de oportunidades que resultaram em venda.\nCálculo: leads ganhos ÷ total de leads que entraram no período × 100.'],['Receita fechada',money(data.revenue),'vendas ganhas no período','Valor total das oportunidades convertidas em venda.\nCálculo: soma dos valores dos leads em Ganho pela data de fechamento.'],['Pipeline',money(data.pipeline),'oportunidades em aberto','Valor potencial das oportunidades que ainda estão abertas.\nCálculo: soma dos valores dos leads que entraram no período e não estão em Ganho ou Perdido.'],['Ticket médio',money(data.ticket),'por venda fechada','Valor médio das vendas concluídas.\nCálculo: receita fechada ÷ quantidade de vendas ganhas.']]:[['Receita fechada',money(data.revenue),data.wins.length+' venda'+(data.wins.length===1?'':'s')+' ganha'+(data.wins.length===1?'':'s'),'Valor total das oportunidades convertidas em venda.\nCálculo: soma dos valores dos leads em Ganho pela data de fechamento.','primary'],['Leads ativos',data.open.length,'em acompanhamento','Quantidade de oportunidades comerciais que continuam em andamento.\nCálculo: leads que não estão marcados como Ganho ou Perdido.'],['Conversão',data.conversion.toFixed(1)+'%',data.wins.length+' ganho'+(data.wins.length===1?'':'s'),'Percentual de oportunidades que resultaram em venda.\nCálculo: leads ganhos ÷ total de leads que entraram no período × 100.'],['Pipeline',money(data.pipeline),'negócios em curso','Valor potencial das oportunidades que ainda estão abertas.\nCálculo: soma dos valores dos leads que entraram no período e não estão em Ganho ou Perdido.'],['Ticket médio',money(data.ticket),'por venda fechada','Valor médio das vendas concluídas.\nCálculo: receita fechada ÷ quantidade de vendas ganhas.']];return list.map(x=>'<article class="kpi '+(x[4]||'')+'"><small>'+x[0]+tip('Explicar '+x[0],x[3])+'</small><strong>'+x[1]+'</strong><span>'+x[2]+'</span></article>').join('')}
function funnel(seller='',closed=false){const input=entered(seller),show=closed?stages:stages.slice(0,5),data=show.map(stage=>{const set=input.filter(l=>l.stage===stage);return{stage,count:set.length,value:set.reduce((a,l)=>a+l.value,0)}}),total=data.filter(x=>!['Ganho','Perdido'].includes(x.stage)).reduce((a,x)=>a+x.value,0),max=Math.max(...data.map(x=>x.value),1);return data.map(x=>{const part=total&&!['Ganho','Perdido'].includes(x.stage)?x.value/total*100:0,detail=x.stage+'\n'+x.count+' oportunidade'+(x.count===1?'':'s')+'\n'+money(x.value)+(!['Ganho','Perdido'].includes(x.stage)?'\n'+part.toFixed(1)+'% do pipeline aberto':''),rule=definitions[x.stage]+'\n\nRegra: '+x.count+' oportunidade'+(x.count===1?'':'s')+' nesta etapa no período.';return '<div class="pipeline-row"><div class="pipeline-label"><span>'+x.stage+'</span>'+tip('Explicar etapa '+x.stage,rule)+'</div><button class="funnel-bar tooltip-trigger" type="button" aria-label="Detalhes da etapa '+x.stage+'" aria-expanded="false" data-tooltip="'+esc(detail)+'"><span class="bar-fill" style="width:'+(x.value?Math.max(7,x.value/max*100):0)+'%"></span></button><div class="pipeline-meta"><b>'+x.count+' oportunidade'+(x.count===1?'':'s')+'</b><span>'+money(x.value)+'</span></div></div>'}).join('')}
function bars(target,seller=''){const y=Number(state.period.slice(0,4)),m=Number(state.period.slice(5));const labels=[];for(let i=5;i>=0;i--){const d=new Date(y,m-1-i,1);labels.push({key:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),label:months[d.getMonth()].slice(0,3)})}const scope=all(seller).filter(l=>l.stage==='Ganho'),values=labels.map(x=>scope.filter(l=>same(l.closedDate,x.key)).reduce((a,l)=>a+l.value,0)),max=Math.max(...values,1);$(target).innerHTML=labels.map((x,i)=>'<div class="revenue-bar"><button class="tooltip-trigger" type="button" aria-label="Receita de '+x.label+'" aria-expanded="false" data-tooltip="'+esc(x.label+'/'+x.key.slice(0,4)+'\nReceita fechada: '+money(values[i]))+'" style="height:'+(values[i]?Math.max(8,values[i]/max*100):3)+'%"></button><span>'+x.label+'</span></div>').join('')}
function ranked(list,field){const data=[...new Set(list.map(x=>x[field]))].map(name=>({name,count:list.filter(x=>x[field]===name).length})).sort((a,b)=>b.count-a.count),max=Math.max(...data.map(x=>x.count),1);return data.length?data.map(x=>'<div class="origin-row"><span>'+esc(x.name)+'</span><div class="bar-track"><span class="bar-fill" style="width:'+(x.count/max*100)+'%"></span></div><b>'+x.count+'</b></div>').join(''):'<p class="empty">Sem registros neste período.</p>'}
function chip(stage){return '<span class="chip '+key(stage)+'">'+stage+'</span>'}
function renderDashboard(){const seller=state.dashboardSeller,data=metric(seller);$('#lead-count').textContent=leads.length;$('#overview').innerHTML=kpis(data);$('#pipeline-total').textContent=money(data.pipeline);$('#pipeline-list').innerHTML=funnel(seller);bars('#revenue-chart',seller);$('#origin-list').innerHTML=ranked(entered(seller),'origin');const list=sellers.map(name=>({name,...metric(name)})).sort((a,b)=>b.revenue-a.revenue);$('#seller-summary').innerHTML='<div class="seller-summary">'+list.map(x=>'<button type="button" class="seller-line profile-link" data-seller="'+x.name+'"><span class="seller-avatar">'+x.name[0]+'</span><span class="seller-info"><b>'+x.name+'</b><span>'+x.open.length+' leads ativos</span></span><strong>'+money(x.revenue)+'</strong></button>').join('')+'</div>'}
function renderLeads(){const q=$('#search').value.trim().toLowerCase(),stage=$('#stage-filter').value,seller=$('#seller-filter').value,list=entered().filter(l=>(!q||l.name.toLowerCase().includes(q)||l.company.toLowerCase().includes(q))&&(!stage||l.stage===stage)&&(!seller||l.seller===seller)).sort((a,b)=>b.date.localeCompare(a.date));$('#lead-rows').innerHTML=list.length?list.map(l=>'<tr><td><b>'+esc(l.name)+'</b><small>'+esc(l.company)+'</small></td><td>'+l.seller+'</td><td>'+esc(l.product)+'</td><td>'+esc(l.origin)+'</td><td>'+chip(l.stage)+'</td><td>'+money(l.value)+'</td><td>'+dateText(l.date)+'</td><td><button type="button" class="text-button edit-lead" data-id="'+l.id+'">Editar</button></td></tr>').join(''):'<tr><td colspan="8">Nenhum lead encontrado neste período.</td></tr>'}
function renderPipeline(){const open=opened(state.dashboardSeller);$('#pipeline-open-value').textContent=money(open.reduce((a,l)=>a+l.value,0));$('#kanban').innerHTML=stages.slice(0,5).map(stage=>{const group=open.filter(l=>l.stage===stage).sort((a,b)=>b.value-a.value);return '<article class="kanban-column"><header><span>'+stage+'</span><span>'+group.length+'</span></header><div class="kanban-cards">'+(group.map(l=>'<article class="lead-card"><b>'+esc(l.name)+'</b><span>'+esc(l.company)+'</span><footer><span>'+l.seller+'</span><b>'+money(l.value)+'</b></footer></article>').join('')||'<p class="empty">Sem oportunidades.</p>')+'</div></article>'}).join('')}
function renderSellers(){$('#seller-rows').innerHTML=sellers.map(name=>{const d=metric(name);return '<tr><td><div class="seller-name"><span class="seller-avatar">'+name[0]+'</span><b>'+name+'</b></div></td><td>'+d.open.length+'</td><td>'+d.wins.length+'</td><td>'+d.conversion.toFixed(1)+'%</td><td>'+money(d.pipeline)+'</td><td>'+money(d.revenue)+'</td><td><button type="button" class="text-button profile-link" data-seller="'+name+'">Ver perfil</button></td></tr>'}).join('')}
function renderProfile(){if(!state.profileSeller)return;const d=metric(state.profileSeller);$('#seller-profile-name').textContent=state.profileSeller==='Júlia'?'Júlia Basilio':state.profileSeller;$('#seller-period-note').textContent=periodLabel();$('#seller-overview').innerHTML=kpis(d,true);$('#seller-funnel').innerHTML=funnel(state.profileSeller,true);bars('#seller-revenue',state.profileSeller);$('#product-list').innerHTML=ranked(entered(state.profileSeller),'product');const ref=new Date(state.period+'-28T12:00:00'),attention=opened(state.profileSeller).filter(l=>(ref-new Date(l.date+'T12:00:00'))/86400000>10).sort((a,b)=>a.date.localeCompare(b.date));$('#attention-list').innerHTML=attention.length?attention.map(l=>'<div class="attention"><b>'+esc(l.name)+'</b><span>'+l.stage+' · entrada em '+dateText(l.date)+'</span></div>').join(''):'<p class="empty">Nenhum lead requer atenção neste período.</p>';const recent=entered(state.profileSeller).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$('#recent-rows').innerHTML=recent.length?recent.map(l=>'<tr><td>'+esc(l.name)+'</td><td>'+esc(l.company)+'</td><td>'+chip(l.stage)+'</td><td>'+money(l.value)+'</td><td>'+dateText(l.date)+'</td></tr>').join(''):'<tr><td colspan="5">Nenhum lead neste período.</td></tr>'}
function renderCriteria(){$('#criteria-list').innerHTML=stages.map(s=>'<div><b>'+s+'</b><p>'+definitions[s]+'</p></div>').join('')}
function bind(){document.querySelectorAll('.profile-link').forEach(b=>b.onclick=()=>{state.profileSeller=b.dataset.seller;setView('seller-profile')});document.querySelectorAll('.edit-lead').forEach(b=>b.onclick=()=>openLead(leads.find(l=>String(l.id)===b.dataset.id)));icons()}
function render(){renderDashboard();renderLeads();renderPipeline();renderSellers();renderProfile();renderCriteria();bind()}
function setView(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const label={dashboard:'Dashboard',leads:'Leads',pipeline:'Pipeline',sellers:'Vendedores','seller-profile':'Perfil do vendedor',about:'Sobre o projeto'}[view];$('#page-title').textContent=label;$('#mobile-page-title').textContent=label;$('.dashboard-only').style.display=view==='dashboard'?'':'none';closeDrawer();window.scrollTo({top:0,behavior:'smooth'})}
function controls(){const periods=[];for(let y=2025;y<=2026;y++)for(let m=1;m<=12;m++)periods.push(y+'-'+String(m).padStart(2,'0'));$('#period-select').innerHTML=periods.map(p=>'<option value="'+p+'" '+(p===state.period?'selected':'')+'>'+months[Number(p.slice(5))-1]+' de '+p.slice(0,4)+'</option>').join('');$('#dashboard-seller').insertAdjacentHTML('beforeend',sellers.map(v=>'<option value="'+v+'">'+v+'</option>').join(''));['stage-filter','seller-filter'].forEach(id=>$( '#'+id).insertAdjacentHTML('beforeend',(id==='stage-filter'?stages:sellers).map(v=>'<option value="'+v+'">'+v+'</option>').join('')))}
const modal=$('#lead-modal'),form=$('#lead-form');
function formState(){const stage=form.elements.stage.value;form.classList.toggle('show-closing',stage==='Ganho');form.classList.toggle('show-loss',stage==='Perdido');form.elements.lossReason.required=stage==='Perdido'}
function openLead(lead){form.reset();$('#lead-form-title').textContent=lead?'Editar lead':'Novo lead';$('#lead-submit').textContent=lead?'Salvar alterações':'Cadastrar lead';if(lead)Object.entries(lead).forEach(x=>{if(form.elements[x[0]])form.elements[x[0]].value=x[1]||''});else{form.elements.id.value='';form.elements.date.value=state.period+'-15';form.elements.closedDate.value=state.period+'-15'}formState();modal.showModal();document.body.classList.add('modal-open');form.elements.name.focus()}
function closeModal(){modal.close();document.body.classList.remove('modal-open')}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show-toast');setTimeout(()=>node.classList.remove('show-toast'),2600)}
form.onsubmit=e=>{e.preventDefault();const data=normal(Object.fromEntries(new FormData(form)));if(data.stage==='Ganho'&&!data.closedDate)data.closedDate=state.period+'-15';if(data.stage!=='Ganho')data.closedDate='';if(data.stage!=='Perdido')data.lossReason='';if(data.id){leads=leads.map(l=>String(l.id)===String(data.id)?data:l);toast('Lead atualizado e indicadores recalculados.')}else{data.id='lead-'+Date.now();leads.push(data);toast('Lead cadastrado e indicadores recalculados.')}localStorage.setItem(storageKey,JSON.stringify(leads));render();closeModal();setView('leads')};
let activeTip=null,tipTimer;const popup=$('#tooltip');
function position(target){const r=target.getBoundingClientRect(),gap=10,margin=12,w=popup.offsetWidth,h=popup.offsetHeight;let top=r.top-h-gap;if(top<margin)top=r.bottom+gap;if(top+h>innerHeight-margin)top=Math.max(margin,innerHeight-h-margin);let left=r.left+r.width/2-w/2;left=Math.max(margin,Math.min(left,innerWidth-w-margin));popup.style.top=top+'px';popup.style.left=left+'px'}
function openTip(target){const text=target.dataset.tooltip;if(!text)return;clearTimeout(tipTimer);if(activeTip&&activeTip!==target)activeTip.setAttribute('aria-expanded','false');activeTip=target;popup.textContent=text;popup.hidden=false;target.setAttribute('aria-expanded','true');requestAnimationFrame(()=>position(target))}
function closeTip(){if(activeTip)activeTip.setAttribute('aria-expanded','false');popup.hidden=true;activeTip=null}
function later(){clearTimeout(tipTimer);tipTimer=setTimeout(()=>{if(!popup.matches(':hover'))closeTip()},120)}
document.addEventListener('pointerover',e=>{const t=e.target.closest('.tooltip-trigger');if(t&&e.pointerType==='mouse')openTip(t)});
document.addEventListener('pointerout',e=>{const t=e.target.closest('.tooltip-trigger');if(t&&e.pointerType==='mouse'&&!e.relatedTarget?.closest('.tooltip-trigger,.orvia-tooltip'))later()});
popup.onpointerenter=()=>clearTimeout(tipTimer);popup.onpointerleave=later;
let lastPointerType='mouse';
document.addEventListener('pointerdown',e=>{lastPointerType=e.pointerType||'mouse'});
document.addEventListener('click',e=>{const t=e.target.closest('.tooltip-trigger');if(t){e.preventDefault();if(activeTip===t&&lastPointerType==='touch')closeTip();else openTip(t)}else if(!e.target.closest('.orvia-tooltip'))closeTip()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTip();const t=e.target.closest('.tooltip-trigger');if(t&&(e.key==='Enter'||e.key===' ')){e.preventDefault();activeTip===t?closeTip():openTip(t)}});
addEventListener('resize',()=>activeTip&&position(activeTip));
function openDrawer(){document.body.classList.add('drawer-open');$('.menu-toggle').setAttribute('aria-expanded','true')}
function closeDrawer(){document.body.classList.remove('drawer-open');$('.menu-toggle').setAttribute('aria-expanded','false')}
document.querySelectorAll('[data-open-drawer]').forEach(b=>b.onclick=openDrawer);document.querySelectorAll('[data-close-drawer]').forEach(b=>b.onclick=closeDrawer);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('.new-lead').forEach(b=>b.onclick=()=>openLead());document.querySelectorAll('.dialog-close,.cancel').forEach(b=>b.onclick=closeModal);$('#lead-stage').onchange=formState;$('#dashboard-seller').onchange=e=>{state.dashboardSeller=e.target.value;render()};$('#period-select').onchange=e=>{state.period=e.target.value;render()};$('#search').oninput=renderLeads;$('#stage-filter').onchange=renderLeads;$('#seller-filter').onchange=renderLeads;
function closeWelcome(){$('#welcome').close();localStorage.setItem(welcomeKey,'seen')}$('.welcome-button').onclick=closeWelcome;$('#welcome .dialog-close').onclick=closeWelcome;
icons();controls();render();if(!localStorage.getItem(welcomeKey))$('#welcome').showModal();
